version: '3.8'

services:
    music-db:
        image: postgres:14
        restart: always
        ports:
            - '5432:5432'    
        volumes:
            - ./db_data/music:/var/lib/postgresql/data
        env_file:
            - .env    
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "devdb", "-U","postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
    user-db:
        image: postgres:14
        restart: always
        ports:
            - '5433:5432'
        expose:
            - "5433"        
        volumes:
            - ./db_data/users:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${USERDB_POSTGRES_DB}
            POSTGRES_USER:  ${USERDB_POSTGRES_USER}
            POSTGRES_PASSWORD:  ${USERDB_POSTGRES_PASSWORD}  
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "userdb", "-U","postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10        
    migrate-1:
        image: migrate/migrate
        restart: on-failure
        depends_on:
          music-db:
            condition: service_healthy   
        volumes:
            - ./music/migrations:/migrations/music
        command:
          [ "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_IP}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable" , "-path", "/migrations/music", "up" ]
    migrate-2:
        image: migrate/migrate
        restart: on-failure
        depends_on:
          music-db:
            condition: service_healthy   
        volumes:
            - ./gateway/migrations:/migrations/gateway
        command:
          [ "-database",  "postgres://${USERDB_POSTGRES_USER}:${USERDB_POSTGRES_PASSWORD}@${USERDB_POSTGRES_IP}:${USERDB_POSTGRES_PORT}/${USERDB_POSTGRES_DB}?sslmode=disable" , "-path", "/migrations/gateway", "up" ]     
    gateway-redis:
        image: redis:6.2
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock      
        ports:
          - 6379:6379       
    gateway:
        build: 
          context: ./gateway/app
          dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - ./configs:/configs
            - ./cert:/cert
        ports:
          - 8080:8080    
          - 8081:8081    
        depends_on:
          - user-db
          - gateway-redis 
    music:
        build: 
          context: ./music/app
          dockerfile: Dockerfile
        ports:
          - 30000:30000  
        env_file:
            - .env
        volumes:
            - ./configs:/configs
            - ./cert:/cert
    email:
        build: 
          context: ./email/app
          dockerfile: Dockerfile
        ports:
          - 30001:30001  
        env_file:
            - .env
        volumes:
            - ./configs:/configs
            - ./cert:/cert
        depends_on:
          - nats                   
    nats:
        image: nats:2.8.4-alpine3.15
        command: 
            "-js"
        ports:
          - 4222:4222
        expose:
          - "4222"
    jaeger:
      image: "jaegertracing/all-in-one:1.22"
      ports:
        - "16686:16686"
        - "6831:6831"             
    prometheus:
        image: "prom/prometheus:v2.21.0"
        ports:
          - "9090:9090"
        command:
          - "--config.file=/etc/prometheus/prometheus.yml"
        volumes:
          - "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    grafana:
        image: grafana/grafana:6.1.6
        environment:
          - GF_AUTH_DISABLE_LOGIN_FORM=true
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
          - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
          - GF_USERS_ALLOW_SIGN_UP=false
        ports:
          - "3000:3000"
        volumes:
          - ./grafana/provisioning:/etc/grafana/provisioning
          - ./grafana/dashboards:/var/lib/grafana/dashboards     



        