version: '3.8'

services:
    postgres:
        image: postgres:14
        restart: always
        ports:
            - '5432:5432'    
        volumes:
            - ./db_data:/var/lib/postgresql/data
        env_file:
            - .env    
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "devdb", "-U","postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
    migrate:
        image: migrate/migrate
        restart: on-failure
        depends_on:
          postgres:
            condition: service_healthy   
        volumes:
            - ./music/migrations:/migrations
        command:
          [ "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_IP}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable" , "-path", "/migrations", "up" ]
    user:
        build: 
          context: ./user/app
          dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - ./configs:/configs    



        