version: '3'

services:
    postgres:
        image: postgres:12
        restart: always
        ports:
            - '5432:5432'    
        volumes:
            - ./db_data:/var/lib/postgresql/data
            - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
        env_file:
            - .env    
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "devdb", "-U","postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
    migrate:
        image: migrate/migrate
        restart: on-failure
        depends_on:
          postgres:
            condition: service_healthy
        volumes:
          - ./server/migrations:/migrations
        command:
          [ "-database",  "postgres://postgres:postgres@postgres:5432/devdb?sslmode=disable" , "-path", "/migrations", "up" ]

        